# ansible-playbook --sudo test_ctakes.yml --user=root --ask-sudo-pass
--- 
# NB: need to run with -K for sudo access
# using local symlink to /opt/nlp and then copying to root of build directory
# all MM files located in kube/metamap/files
- hosts: 127.0.0.1
  become: true
  become_method: sudo
  become_user: root
  become_ask_pass: True
  connection: local
  vars:
    path_test: /opt/nlp
    mm: ../files/public_mm_linux_main_2016v2.tar.bz2
    java_mm: ../files/public_mm_linux_javaapi_2016v2.tar.bz2
    uima_mm: ../files/public_mm_uima_2014.zip
    java_home: /usr/lib/jvm/java-8-openjdk-amd64
  tasks:
  - name: Extract MM Main
    unarchive: src={{mm}}
               dest={{path_test}}
  - name: Extract Java MM
    unarchive: src={{java_mm}}
               dest={{path_test}}
  - name: Extract UIMA MM
    unarchive: src={{uima_mm}}
               dest={{path_test}}
  - name: Install MM
    shell: './public_mm/bin/install.sh'
